// <auto-generated />
using System;
using BugetApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugetApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BugetApi.Model.Cheltuiala", b =>
                {
                    b.Property<int>("CheltuialaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Denumire")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCheltuialaObligatorie")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCheltuit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeUtilizator")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Suma")
                        .HasColumnType("INTEGER");

                    b.HasKey("CheltuialaId");

                    b.HasIndex("DepartamentId");

                    b.ToTable("Cheltuialas");
                });

            modelBuilder.Entity("BugetApi.Model.Departament", b =>
                {
                    b.Property<int>("DepartamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Denumire")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeUtilizator")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("DepartamentId");

                    b.ToTable("Departaments");
                });

            modelBuilder.Entity("BugetApi.Model.Cheltuiala", b =>
                {
                    b.HasOne("BugetApi.Model.Departament", "Departament")
                        .WithMany("ListaCheltuieli")
                        .HasForeignKey("DepartamentId");

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("BugetApi.Model.Departament", b =>
                {
                    b.Navigation("ListaCheltuieli");
                });
#pragma warning restore 612, 618
        }
    }
}
